title: ObsidianOS Docs
description: Documentation for ObsidianOS
theme: just-the-docs
baseurl: "/docs"
url: https://obsidian-os.github.io
color_scheme: dark
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
aux_links:
  Home: https://obsidian-os.github.io/
back_to_top: true
back_to_top_text: "Back to top"
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/Obsidian-OS/docs"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"
